/**
 * PerfectFreehandMode — Steve Ruiz's perfect-freehand technique behind the
 * DrawingMode strategy contract with `id = 'perfect-freehand'`.
 *
 * Unlike the centerline-stamping modes (Classic, Square Bezier), this mode
 * produces a variable-width, pressure-responsive stroke as a single **filled
 * outline polygon** around the input path. The outline is generated by
 * perfect-freehand's `getStroke`, which returns an array of `[x, y]` points
 * describing a closed polygon that surrounds the input points.
 *
 * Because the outline is recomputed from the whole point set as it grows, this
 * mode cannot use the append-only geometry assumption the other modes rely on.
 * The rendering split is therefore:
 *   - during the stroke, the evolving outline is painted on the **Temp_Overlay**
 *     once per frame via `renderPreview` (Req 4.1);
 *   - at `end()` (strokeEnd), the **final** outline is filled onto the
 *     **Main_Canvas exactly once** (Req 4.2), keeping the main context
 *     append-only like the other modes.
 *
 * Input points carry optional `pressure`. When a point lacks pressure a default
 * is substituted so the stroke still renders (with uniform width) rather than
 * failing (Req 7.3). The serialized stroke records the input points with
 * `pressure` plus the mode `options` (size, thinning, smoothing, streamline)
 * needed to regenerate an identical outline on replay (Req 4.3).
 *
 * The mode owns all per-stroke state and resets it between strokes. Contexts and
 * style are handed in by the engine via `begin(point, style)`; `replay(stroke,
 * ctx)` rebuilds the identical outline from the serialized points and options
 * and fills it once onto the given main context.
 */

import { getStroke } from 'perfect-freehand';
import { DrawingMode } from './DrawingMode.js';

/** Mode options forwarded to perfect-freehand's `getStroke`. */
const DEFAULT_OPTIONS = {
  size: 6,
  thinning: 0.5,
  smoothing: 0.5,
  streamline: 0.5,
};

/**
 * Substituted when an input point carries no pressure (mouse input, or a device
 * reporting 0). A mid-scale default yields a uniform-width stroke (Req 7.3).
 */
const DEFAULT_PRESSURE = 0.5;

export class PerfectFreehandMode extends DrawingMode {
  constructor() {
    super();
    // Style / context supplied by the engine via begin() and replay(). Defaults
    // mirror the engine's own so a standalone mode still behaves sensibly.
    this._ctx = null;
    this._tempCtx = null;
    this._colorPrefix = 'rgba(0,0,0';
    this._options = { ...DEFAULT_OPTIONS };

    // Per-stroke state, owned by the mode and reset between strokes.
    this._points = [];
  }

  /** @returns {string} */
  get id() {
    return 'perfect-freehand';
  }

  /**
   * Apply the style/context bundle handed in by the engine. Only provided keys
   * are updated so callers can pass a partial bundle. Mode-specific options may
   * arrive either as top-level keys or nested under `options`.
   * @param {object} style
   */
  _applyStyle(style = {}) {
    if (style.ctx !== undefined) this._ctx = style.ctx;
    if (style.tempCtx !== undefined) this._tempCtx = style.tempCtx;
    if (style.colorPrefix !== undefined) this._colorPrefix = style.colorPrefix;
    this._options = this._resolveOptions(style);
  }

  /**
   * Merge mode options from a style bundle (top-level keys or `options`) over
   * the defaults.
   * @param {object} source
   * @returns {{size:number, thinning:number, smoothing:number, streamline:number}}
   */
  _resolveOptions(source = {}) {
    const nested = source.options ?? {};
    const pick = (key) => {
      if (source[key] !== undefined) return source[key];
      if (nested[key] !== undefined) return nested[key];
      return DEFAULT_OPTIONS[key];
    };
    return {
      size: pick('size'),
      thinning: pick('thinning'),
      smoothing: pick('smoothing'),
      streamline: pick('streamline'),
    };
  }

  /** Reset per-stroke state for a fresh stroke. */
  _resetStrokeState() {
    this._points = [];
  }

  /**
   * Normalize an input point, substituting a default pressure when absent so
   * the stroke still renders with uniform width (Req 7.3).
   * @param {{ x:number, y:number, pressure?:number }} point
   * @returns {{ x:number, y:number, pressure:number }}
   */
  _normalizePoint(point) {
    const pressure = typeof point.pressure === 'number' ? point.pressure : DEFAULT_PRESSURE;
    return { x: point.x, y: point.y, pressure };
  }

  /**
   * Begin a stroke (pointer down). Seeds the point buffer with the first
   * (pressure-normalized) point. The main context is intentionally left
   * untouched: perfect-freehand commits exactly one fill at `end()`.
   * @param {{ x:number, y:number, pressure?:number }} point
   * @param {object} [style]
   */
  begin(point, style = {}) {
    this._applyStyle(style);
    this._resetStrokeState();
    this._clearTemp();
    this._points.push(this._normalizePoint(point));
  }

  /**
   * Add a subsequent sample (pointer move). Accumulates the point only; the
   * outline is repainted on the temp overlay via renderPreview() and committed
   * to the main context once at end().
   * @param {{ x:number, y:number, pressure?:number }} point
   */
  addPoint(point) {
    this._points.push(this._normalizePoint(point));
  }

  /**
   * Paint the evolving outline onto the temp overlay (Req 4.1). Pure overlay
   * operation: it never mutates the committed main-context result, and is safe
   * to call once per animation frame.
   * @param {CanvasRenderingContext2D} [tempCtx]
   */
  renderPreview(tempCtx) {
    if (tempCtx !== undefined) this._tempCtx = tempCtx;
    if (!this._tempCtx) return;
    this._clearTemp();
    if (this._points.length === 0) return;

    const outline = this._outline(this._points, this._options, false);
    this._fillOutline(outline, this._tempCtx, this._fillColor());
  }

  /**
   * End a stroke (pointer up). Fills the FINAL outline onto the main context
   * exactly once (Req 4.2), clears the live preview, and returns the
   * serializable stroke: input points with `pressure` plus the mode `options`
   * needed to regenerate an identical outline on replay (Req 4.3).
   * @returns {{ mode:string, color:string, options:object, points:object[] }}
   */
  end() {
    const points = this._points;
    const outline = this._outline(points, this._options, true);
    this._fillOutline(outline, this._ctx, this._fillColor());

    const stroke = {
      mode: this.id,
      color: this._colorPrefix,
      options: { ...this._options },
      points: points.map((p) => ({ x: p.x, y: p.y, pressure: p.pressure })),
    };

    this._resetStrokeState();
    this._clearTemp();
    return stroke;
  }

  /**
   * Handle a single tap (dot): a one-point outline filled once onto the main
   * context.
   * @param {{ x:number, y:number, pressure?:number }} point
   * @param {object} [style]
   * @returns {{ mode:string, color:string, options:object, points:object[] }}
   */
  tap(point, style = {}) {
    this._applyStyle(style);
    this._resetStrokeState();

    const normalized = this._normalizePoint(point);
    const outline = this._outline([normalized], this._options, true);
    this._fillOutline(outline, this._ctx, this._fillColor());

    return {
      mode: this.id,
      color: this._colorPrefix,
      options: { ...this._options },
      points: [{ x: normalized.x, y: normalized.y, pressure: normalized.pressure }],
    };
  }

  /**
   * Reproduce a previously serialized perfect-freehand stroke onto the given
   * main context, rebuilding the identical outline from the stored points and
   * options and filling it once (Req 4.3).
   * @param {{ color?:string, options?:object, points:object[] }} stroke
   * @param {CanvasRenderingContext2D} ctx
   */
  replay(stroke, ctx) {
    const { points } = stroke;
    if (!points || points.length === 0) return;

    const savedColor = this._colorPrefix;
    if (stroke.color !== undefined) this._colorPrefix = stroke.color;
    const options = this._resolveOptions({ options: stroke.options });

    const normalized = points.map((p) => this._normalizePoint(p));
    const outline = this._outline(normalized, options, true);
    this._fillOutline(outline, ctx, this._fillColor());

    this._colorPrefix = savedColor;
  }

  // --- Private helpers ---

  /** Fully-opaque committed fill color. */
  _fillColor() {
    return `${this._colorPrefix},1)`;
  }

  /**
   * Generate the outline polygon for a point set via perfect-freehand.
   * @param {Array<{x:number,y:number,pressure:number}>} points
   * @param {object} options - size/thinning/smoothing/streamline
   * @param {boolean} last - whether to treat the points as a completed stroke
   * @returns {number[][]} array of `[x, y]` outline points
   */
  _outline(points, options, last) {
    return getStroke(points, { ...options, last });
  }

  /**
   * Fill a closed outline polygon as a single path (moveTo the first point,
   * lineTo the rest, closePath, fill). No-op for an empty outline.
   * @param {number[][]} outline
   * @param {CanvasRenderingContext2D} ctx
   * @param {string} fillColor
   */
  _fillOutline(outline, ctx, fillColor) {
    if (!ctx || !outline || outline.length === 0) return;
    ctx.fillStyle = fillColor;
    ctx.beginPath();
    ctx.moveTo(outline[0][0], outline[0][1]);
    for (let i = 1; i < outline.length; i += 1) {
      ctx.lineTo(outline[i][0], outline[i][1]);
    }
    ctx.closePath();
    ctx.fill();
  }

  _clearTemp() {
    if (!this._tempCtx) return;
    const { canvas } = this._tempCtx;
    this._tempCtx.clearRect(0, 0, canvas.width, canvas.height);
  }
}

export default PerfectFreehandMode;
